apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/hook: Sync
  #   argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: "v1.13.3"
      helm:
        valueFiles:
        - $values/app-of-apps/files/cert-values.yaml
    - repoURL: git@github.com:liormilliger/Portfolio-config.git
      targetRevision: HEAD
      ref: values
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true