apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bitnami/charts.git
    path: "/bitnami/elasticsearch"
    # chart: cert-manager
    targetRevision: HEAD
    helm:
      valueFiles:
        - files/my-es-values.yml
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
