apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  sources:
    # repoURL: https://helm.elastic.co
    # path: "elastic"
    # chart: "elasticsearch"
    # targetRevision: "8.5.1"
    - repoURL: https://github.com/bitnami/charts
      # path: "bitnami/elasticsearch"
      targetRevision: "19.14.1"
      chart: "oci://registry-1.docker.io/bitnamicharts/elasticsearch"
    #   helm:
    #     valueFiles:
    #     - $values/app-of-apps/files/my-es-values.yml
    # - repoURL: git@github.com:liormilliger/Portfolio-config.git
    #   targetRevision: argocd
    #   ref: values
  destination: 
    server: https://kubernetes.default.svc
    namespace: elastic

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
