apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: HEAD
    chart: elasticsearch
    helm:
      valueFiles:
        - ./app-of-apps/files/my-es-values.yml
    server: 'https://kubernetes.default.svc'
    namespace: elastic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
