apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  sources:
    # repoURL: https://helm.elastic.co
    # path: "elastic"
    # chart: "elasticsearch"
    # targetRevision: "8.5.1"
    - repoURL: https://github.com/bitnami/charts.git
      path: "bitnami/elasticsearch"
      targetRevision: HEAD
      chart: "elasticsearch"
      helm:
        valueFiles:
        - $values/app-of-apps/files/my-es-values.yml
    - repoURL: git@github.com:liormilliger/Portfolio-config.git
      targetRevision: argocd
      ref: values
  destination: 
    server: https://kubernetes.default.svc
    namespace: elastic

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
