apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: fluentd
      # <parse>
      #   @type "/^(?<host>[^ ]*) [^ ]* [^ ]* \[(?<time>[^\]]*)\] \"(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?\" (?<code>[^ ]*) (?<size>[^ ]*)(?: \"(?<referer>[^\"]*)\" \"(?<agent>[^\"]*)\")?$"
      #   time_format %d/%b/%Y:%H:%M:%S %z
      # </parse>
data:
  fluentd.conf: |

    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      port 9880
    </source>
    # <source>
    #   @type forward
    #   port 5000
    # </source>
    # Throw the healthcheck to the standard output instead of forwarding it
    # <match fluentd.healthcheck>
    #   @type stdout
    # </match>
    # Fetching logs from DEFAULT CONTAINER FOLDER (ON NODE) AND PARSING
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format regexp
          expression /^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{9}Z) (?<stream>stdout|stderr) [PF] (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format regexp
          # expression /^(?<host>\S+) - - \[(?<time>[^\]]+)\] "(?<request>[^"]+)" (?<status>\d+) (?<size>\S+)/
          expression /^(?<host>\S+) - - \[(?<time>[^\]]+)\] "(?<request>[^"]+)" (?<status>\d+)( (?<size>\S+))?/
          time_format %d/%b/%Y:%H:%M:%S %z
        </pattern>
      </parse>
    </source>

    <filter kubernetes.**>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
    </filter>
    
    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**kube-system**.log>
      @type null
    </match>
    
    <match **>
      # @id elasticsearch
      @type elasticsearch
      log_level info
      include_tag_key true
      host elasticsearch.elastic.svc.cluster.local
      port 9200
      path ""
      scheme http
      # ssl_verify true
      # ssl_version TLSv1_2
      type_name _doc
      logstash_format true
      logstash_prefix logstash
      # include_tag_key true
      # tag_key @log_name
      <buffer>
        flush_interval 1s
      </buffer>
    </match>

    <match kubernetes.**>
      @type stdout
    </match>


