apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: fluentd
data:
  fluentd.conf: |

    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      port 9880
    </source>

    # Fetching logs from DEFAULT CONTAINER FOLDER (ON NODE) AND PARSING
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
    
    # <filter kubernetes.**>
    #   @type parser
    #   key_name message
    #   reserve_data true
    #   <parse>
    #     @type json
    #     reserve_data true
    #   </parse>
    # </filter>

    # <filter kubernetes.**>
    #   @type grep
    #   <regexp>
    #     key message
    #     pattern /^\{/
    #   </regexp>
    #   <exclude>
    #     key message
    #     pattern /^(?!.*\blevel\b).*$/
    #   </exclude>
    # </filter>
    
    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**kube-system**.log>
      @type null
    </match>

    # <match **>
    #   @type elasticsearch
    #   # @log_level info
    #   host elasticsearch.elastic.svc.cluster.local
    #   port 9200
    #   # scheme http
    #   # index_name fluentd
    #   type_name _doc
    #   logstash_format true
    #   logstash_prefix logstash
    #   include_tag_key true
    #   tag_key @log_name
    #   <buffer>
    #     flush_interval 5s
    #   </buffer>
    # </match>

    <match kubernetes.**>
      @type stdout
    </match>

