apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: fluentd
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: argocd
    targetRevision: "v2.2.1"
    helm:
      valueFiles:
        - files/fluentd-values.yaml
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    # syncOptions:
    # - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
