aggregator:
  ## @param aggregator.enabled Enable Fluentd aggregator statefulset
  ##
  enabled: false

forwarder:
  ## @param forwarder.enabled Enable forwarder daemonset
  ##
  enabled: true
  ## @param forwarder.configFile Name of the config file that will be used by Fluentd at launch under the `/opt/bitnami/fluentd/conf` directory
  ##
  configFile: fluentd.conf
  ## @param forwarder.configMap Name of the config map that contains the Fluentd configuration files
  ## If not specified, one will be created by default
  ##
  configMap: fluentd-config
  ## @param forwarder.extraEnvVars Extra environment variables to pass to the container
  extraEnvVars:
    - name: ELASTICSEARCH_HOST
      value: "elasticsearch.elastic.svc.cluster.local"
    - name: ELASTICSEARCH_PORT
      value: "9200"
