apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    path: "elastic"
    chart: "kibana"
    targetRevision: "8.5.1"
    # repoURL: https://github.com/bitnami/charts.git
    # path: "bitnami/elasticsearch"
    # targetRevision: HEAD
    # chart: "elasticsearch-19.17.0"
    # helm:
    #   valueFiles:
    #     - ./app-of-apps/files/my-es-values.yml
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
