apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "55.11.0"
    # helm:
    #   valueFiles:
    #     - files/prometheus-values.yaml
    # https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
  destination: 
    server: https://kubernetes.default.svc
    namespace: kube-prometheus-stack

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true