# Certificate resource
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: liorm-portfolio-tls
spec:
  secretName: liorm-portfolio-tls
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
  - blogitapp.ddnsking.com