# Issuer resource for Let's Encrypt
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: liormdevops@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

---
# Certificate resource
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: liorm-portfolio-tls
spec:
  secretName: liorm-portfolio-tls
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
  - blogitapp.ddnsking.com
