apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: fluentd
  annotations:
    argocd.argoproj.io/hook: PreSync
data:
  fluentd.conf: |

    # Ignore fluentd own events
    <match fluentd.**>
      @type null
    </match>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      port 9880
    </source>

    # Throw the healthcheck to the standard output instead of forwarding it
    # <match fluentd.healthcheck>
    #   @type stdout
    # </match>

    # Fetching logs from DEFAULT CONTAINER FOLDER (ON NODE) AND PARSING
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/containers.log.pos
      time_format %Y-%m-%d %H:%M:%S,%L
      # time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      # tag file.logs
      format none
      read_from_head true
      # <parse>
      #   @type regexp
      # #   expression /^(?<k8s-timestamp>.+)/
      #   # # \{("[^"]*"\s*,\s*)*"[^"]*"\s*,\s*"[^"]*"\s*\}/
      #   expression /^(?<k8s-timestamp>.+) (?<stream>stdout|stderr) (?<message>\{.+\}) (?<saxophone>.+)$/
      #   time_format %Y-%m-%d %H:%M:%S,%L
      # </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
    
    # <filter kubernetes.**>
    #   @type parser
    #   key_name message
    #   reserve_time true
    #   reserve_data true
    #   remove_key_name_field true
    #   <parse>
    #     @type regexp
    #     expression /^/\{\\\"level\\\"\:\ \\\"(?<level>[^\"]+)\\\", \\\"message\\\"\:\ \\\"(?<message>[^\"]+)\\\", \\\"time\\\"\:\ \\\"(?<time>[^\"]+)\\\", \\\"method\\\"\:\ \\\"(?<method>[^\"]+)\\\"}/gm/
    #     # expression /^\"(?<method>[A-Z]+) (?<path>[^ ]+) (?<protocol>[^ ]+)\" -- (?<status_code>\d+)$/
    #   </parse>
    # </filter>

    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>

    <match kubernetes.var.log.containers.**kube-system**.log>
      @type null
    </match>

    # <match **>
    #   @type elasticsearch
    #   @log_level info
    #   host elasticsearch.elastic.svc.cluster.local
    #   port 9200
    #   scheme http
    #   index_name fluentd
    #   type_name _doc
    #   logstash_format true
    #   logstash_prefix logstash
    #   include_tag_key true
    #   tag_key @log_name
    #   reconnect_on_error true
    #   <buffer>
    #     @type file
    #     path /var/log/fluentd-buffers/kubernetes.system.buffer
    #     flush_mode interval
    #     retry_type exponential_backoff
    #     flush_thread_count 2
    #     flush_interval 5s
    #     retry_forever
    #     retry_max_interval 30
    #     chunk_limit_size 2M
    #     queue_limit_length 8
    #     overflow_action block
    #   </buffer>
    # </match>

    <match **>
      @type stdout
    </match>

