apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: fluentd

data:
  fluentd.conf: |

    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      port 9880
    </source>

    # Fetching logs from DEFAULT CONTAINER FOLDER (ON NODE) AND PARSING
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.blog
      read_from_head true
      <parse>
        @type regexp
        # expression /^(?<timestamp>.+) (?<stream>stdout|stderr) [^ ]* (?<host>[^ ]*) - - \[(?<time>[^\]]*)\] ".*(?<method>[A-Z]+) (?<path>[^"]*) HTTP\/1\.[01].*" (?<code>\d+) .*$/
        expression /^(?<timestamp>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
        time_format %d/%b/%YT%H:%M:%S %z
      </parse>
    </source>
    
    <filter kubernetes.blog>
      @id filter_parser
      @type parser
      key_name log
      reserve_time true
      reserve_data true
      remove_key_name_field true
      <parse>
        @type regexp
        expression /\"(?<method>[A-Z]+) (?<path>[^ ]+) (?<protocol>[^ ]+)\" (?<status_code>\d+).*$/
      </parse>
    </filter>
    
    <match **>
      # @id elasticsearch
      @type elasticsearch
      # @log_level info
      include_tag_key true
      host elasticsearch.elastic.svc.cluster.local
      port 9200
      # scheme http
      # ssl_verify true
      # ssl_version TLSv1_2
    #   type_name _doc
      logstash_format true
      logstash_prefix logstash
      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>

