{
 "title": "Blog-App Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "ArgoCD CPU and Mem Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ArgoCD Mem Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{namespace=\"argocd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArgoCD cpu usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{namespace=\"argocd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Blog-App metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "total http requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "http_requests_total{pod=\"blog-app-79f75bcbb9-8phjq\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blog Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_duration_seconds{pod=\"blog-app-79f75bcbb9-8phjq\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}