# config:
#   allow_partial_search_results: true

esJavaOpts: "-Xmx3g -Xms3g"

resources:
  requests:
    cpu: "1000m"
    memory: "4Gi"
  limits:
    cpu: "1000m"
    memory: "4Gi"

# Kibana values (subchart)
kibana:
  service:
    ## @param service.ports.http Kubernetes Service port
    ##
    ports:
      http: 5601
    ## @param service.type Kubernetes Service type
    ##
    type: ClusterIP

# Elasticsearch values
global:
  kibanaEnabled: true

master:
  masterOnly: false
  replicaCount: 1
data:
  replicaCount: 0
coordinating:
  replicaCount: 0
ingest:
  replicaCount: 0

sysctlImage:
  ## Enable kernel settings modifier image - not available in GKE Autopilot
  ## See https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
  enabled: true
