# Elasticsearch values
global:
  elasticsearch:
    service:
      name: elasticsearch
      ports:
        restAPI: 9200
  kibanaEnabled: true

master:
  masterOnly: false
  replicaCount: 1
data:
  replicaCount: 0
coordinating:
  replicaCount: 0
ingest:
  replicaCount: 0
# Kibana values (subchart)
kibana:
  service:
    # name: elasticsearch-kibana
    ## @param service.ports.http Kubernetes Service port
    ##
    ports:
      http: 5601
    ## @param service.type Kubernetes Service type
    ##
    type: ClusterIP
# fluent-bit:
#   enabled: true
#   config:
#     service: |
#       [SERVICE]
#           Daemon Off
#           Flush 1
#           Log_Level info
#           Parsers_File /fluent-bit/etc/parsers.conf
#           HTTP_Server On
#           HTTP_Listen 0.0.0.0
#           HTTP_Port 2020
#           Health_Check On
#     inputs: |
#       [INPUT]
#           Name tail
#           Path /var/log/containers/*blog*.log
#           multiline.parser docker, cri
#           Tag kube.*
#           Mem_Buf_Limit 100MB
#           Skip_Long_Lines On

#       [INPUT]
#           Name systemd
#           Tag host.*
#           Systemd_Filter _SYSTEMD_UNIT=kubelet.service
#           Read_From_Tail On
#     filters: |
#       [FILTER]
#           Name kubernetes
#           Match kube.*
#           Merge_Log On
#           Keep_Log Off
#           K8S-Logging.Parser On
#           K8S-Logging.Exclude On
#     outputs: |
#       [OUTPUT]
#           Name es
#           Match kube.*
#           Host elasticsearch
#           Port 9200
#           tls.Off
#           tls.verify Off
#           Logstash_Format On
#           Retry_Limit False

#       [OUTPUT]
#           Name es
#           Match host.*
#           Host elasticsearch
#           Port 9200
#           tls.Off
#           tls.verify Off
#           Logstash_Format On
#           Logstash_Prefix node
#           Retry_Limit False

sysctlImage:
  ## Enable kernel settings modifier image - not available in GKE Autopilot
  ## See https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
  enabled: true
