# Elasticsearch values
global:
  elasticsearch:
    master:
      masterOnly: false
      replicaCount: 1
    data:
      replicaCount: 0
    coordinating:
      replicaCount: 0
    ingest:
      replicaCount: 0
    service:
      name: elasticsearch
      ports:
        restAPI: 9200
  kibanaEnabled: true

# master:
#   masterOnly: false
#   replicaCount: 1
# data:
#   replicaCount: 0
# coordinating:
#   replicaCount: 0
# ingest:
#   replicaCount: 0
# Kibana values (subchart)
kibana:
  service:
    # name: elasticsearch-kibana
    ## @param service.ports.http Kubernetes Service port
    ##
    ports:
      http: 5601
    ## @param service.type Kubernetes Service type
    ##
    type: ClusterIP

sysctlImage:
  ## Enable kernel settings modifier image - not available in GKE Autopilot
  ## See https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
  enabled: true
