apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blog-app-service-monitor
spec:
  selector:
    matchLabels:
      app: blog
  endpoints:
  - port: "5000"
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
    