apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blog-app-SM
spec:
  selector:
    matchLabels:
      app: blog
  endpoints:
  - port: http
    path: /metrics
  # namespaceSelector:
  #   matchNames:
  #   - default
    