apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appSvcName }}
  # namespace: app
  labels:
    app: {{ .Values.appName }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io.scheme: "http"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5000"
spec:
  selector:
    app: {{ .Values.blogapp.appName }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.blogapp.appPort | default 5000 }}
      name: http
      targetPort: {{ .Values.blogapp.appPortName }}
