apiVersion: v1
kind: Service
metadata:
  name: blog-service
  # namespace: app
  labels:
    app: blog
spec:
  selector:
    app: blog
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      name: http
      targetPort: webapp
