apiVersion: v1
kind: Service
metadata:
  name: blog-service
  # namespace: app
  labels:
    app: blog
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io.scheme: "http"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5000"
spec:
  selector:
    app: blog
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      name: http
      targetPort: webapp
