apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #   - blogitapp.ddnsking.com
  #   secretName: some-secret
  rules:
  # - host: blogitapp.ddnsking.com
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.blogapp.appSvcName }}
            port:
              number: {{ .Values.blogapp.appPort | default 5000 }}