apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-app-ingress
  namespace: default
  annotations:
  # for cert-manager annotation check if cluster-issuer or just issuer
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1.2 TLSv1.3"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - blogitapp.ddnsking.com
    - www.blogitapp.ddnsking.com
    secretName: liorm-portfolio-tls
  rules:
  - host: blogitapp.ddnsking.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.blogapp.appSvcName }}
            port:
              number: {{ .Values.blogapp.appPort | default 5000 }}