apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongoApp }}
  # namespace: app
spec:
  selector:
    matchLabels:
      app: {{ .Values.mongoApp }}
  serviceName: {{ .Values.mongoSvc }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.mongoApp }}
    spec:
      containers:
      - name: {{ .Values.mongoApp }}
        image: mongo:5.0
        ports:
        - containerPort: 27017
          name: {{ .Values.mongoApp }}
        env:
        - name: MONGO_INITDB_DATABASE
          value: blog
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        volumeMounts:
        - name: {{ .Values.mongoPV }}
          mountPath: /data/db
        - name: init-database
          mountPath: "/docker-entrypoint-initdb.d/"
        # command:
        # - "mongod"
        # - "--bind_ip_all"
        # - "--replSet"
        # - "demoReplSet"
      volumes:
      - name: init-database
        configMap:
          name: mongo-init-script
      - name: {{ .Values.mongoPV }}
        persistentVolumeClaim:
          claimName: mongo-pvc
  # volumeClaimTemplates:
  # - metadata:
  #     name: {{ .Values.mongoPV }}
  #   spec:
  #     storageClassName: standard
  #     accessModes:
  #       - ReadWriteMany
  #     resources:
  #       requests:
  #         storage: 150Mi

