apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongodb.mongoApp }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mongodb.mongoApp }}
  serviceName: {{ .Values.mongodb.mongoSvc }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.mongoApp }}
    spec:
      initContainers:
      - name: init-config
        image: mongo:5.0
        command: ["bash", "-c", "cp /config/init.js /tmp/init.js && cp /tmp/init.js /docker-entrypoint-initdb.d/init.js"]
        volumeMounts:
        - name: init-config-volume
          mountPath: "/config"
        - name: init-temp
          mountPath: "/tmp"
      containers:
      - name: {{ .Values.mongodb.mongoApp }}
        image: mongo:5.0
        ports:
        - containerPort: {{ .Values.mongodb.mongoPort }}
          name: {{ .Values.mongodb.mongoApp }}
        envFrom:
        - secretRef:
            name: mongo-secrets
        volumeMounts:
        - name: {{ .Values.mongodb.mongoPV }}
          mountPath: /data/db
      volumes:
      - name: init-config-volume
        configMap:
          name: mongo-init-script
      - name: init-temp
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.mongodb.mongoPV }}
    spec:
      storageClassName: {{ .Values.mongopv.scType }}
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.mongopv.volSize }}
