apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.mongoSvc }}
  labels:
    app: {{ .Values.mongodb.mongoApp }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.mongodb.mongoPort | default 27017 }}
  selector:
    app: {{ .Values.mongodb.mongoApp }}

