apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  storageClassName: {{ .Values.mongopv.scType }}
  accessModes:
    - {{ .Values.mongopv.accessMode }}
  capacity:
    storage: {{ .Values.mongopv.volSize }}
  hostPath:
    path: "/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - {{ .Values.mongopv.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mongopv.volSize }}

  