blogapp:
  appName: blog
  appPort: 5000
  appPortName: webapp
  appSvcName: blog-service
  appImage: 644435390668.dkr.ecr.us-east-1.amazonaws.com/liorm-portfolio:1.0.20
  appDNS: blogitapp.ddnsking.com
mongodb:
  mongoApp: mongo
  mongoSvc: mongodb
  mongoPort: 27017
  mongoPV: mongo-data
configmap:
  cmName: blog-conf
mongopv:
  volSize: "8Gi"
  scType: gp2-csi-driver
  accessMode: ReadWriteOnce
Replicas: 1
