blogapp:
  appName: blog
  appPort: 5000
  appPortName: webapp
  appSvcName: blog-service
  appImage: liormilliger/blog-app-prod:1.0.36
  appDNS: blogitapp.ddnsking.com
mongodb:
  mongoApp: mongo
  mongoSvc: mongodb
  mongoPort: 27017
  mongoPV: mongo-data
configmap:
  cmName: blog-conf
mongopv:
  volSize: "150Mi"
  scType: gp2
  accessMode: ReadWriteMany
Replicas: 1
