blogapp:
  appName: blog
  appPort: 5000
  appPortName: webapp
  appSvcName: blog-service
  appImage: 644435390668.dkr.ecr.us-east-1.amazonaws.com/liorm-portfolio:1.0.16
  appDNS: blogitapp.myddns.me
mongodb:
  mongoApp: mongo
  mongoSvc: mongodb
  mongoPort: 27017
  mongoPV: mongo-data
configmap:
  cmName: blog-conf
mongopv:
  volSize: "150Mi"
  scType: gp2
  accessMode: ReadWriteMany
Replicas: 1
